# Generated by Django 3.2.16 on 2022-12-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_topic_blog_blogidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
