# Generated by Django 3.2.16 on 2024-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240506_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
