# Generated by Django 3.2.16 on 2024-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20240511_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile1',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile1',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
