# Generated by Django 3.2.16 on 2024-05-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_subtask_task_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_username',
            field=models.CharField(default='not assigned', max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
