# Generated by Django 3.2.16 on 2024-05-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20240514_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='name',
            new_name='subtask',
        ),
    ]
