# Generated by Django 3.2.16 on 2024-05-24 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignmentcount',
            name='personnel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
