# Generated by Django 3.2.16 on 2024-06-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_client_recurringtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='assigned_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recurring_tasks', to='home.profile1'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='home.profile1'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
