# Generated by Django 3.2.16 on 2024-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20240624_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtask',
            name='assigned_personnel',
        ),
        migrations.RemoveField(
            model_name='recurringtask',
            name='client',
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='assigned_personnel_username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
