# Generated by Django 3.2.16 on 2024-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20240624_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='assigned_personnel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='client',
            field=models.CharField(max_length=100),
        ),
    ]
