# Generated by Django 3.2.16 on 2024-06-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20240624_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='assigned_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recurring_tasks', to='home.profile1'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='home.profile1'),
        ),
    ]
