# Generated by Django 3.2.16 on 2024-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20240624_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Recurrent_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='recurring_tasks', to='home.RecurrentFiles'),
        ),
    ]
