# Generated by Django 3.2.16 on 2024-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20240624_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentfiles',
            name='file',
            field=models.FileField(upload_to='recurrent_files'),
        ),
    ]
