# Generated by Django 3.2.16 on 2024-07-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20240711_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('path', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile1')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurringtask')),
            ],
        ),
    ]
