# Generated by Django 3.2.16 on 2024-07-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_taskdirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTaskDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='home.rtaskdirectory')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurringtask')),
            ],
        ),
        migrations.CreateModel(
            name='RTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recurrent_task_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile1')),
            ],
        ),
        migrations.CreateModel(
            name='RTaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurringtask')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile1')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDirectory',
        ),
    ]
