# Generated by Django 3.2.16 on 2024-07-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20240719_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtaskfile',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='rtaskfile',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='rtaskfile',
            name='status',
        ),
    ]
