# Generated by Django 3.2.16 on 2024-07-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20240721_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtaskfile',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='rtaskfile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.profile1'),
            preserve_default=False,
        ),
    ]
