# Generated by Django 3.2.16 on 2024-07-24 07:14

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_rtaskfile_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtaskfile',
            old_name='created_by',
            new_name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='rtaskfile',
            name='file',
            field=models.FileField(upload_to=apps.home.models.task_file_path),
        ),
    ]
