# Generated by Django 3.2.16 on 2024-07-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20240724_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtaskfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
