# Generated by Django 3.2.16 on 2024-07-29 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0054_rtaskfile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdirectories', to='home.taskdirectory')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='home.task')),
            ],
        ),
    ]
