# Generated by Django 3.2.16 on 2024-07-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20240729_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
