# Generated by Django 3.2.16 on 2024-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
