# Generated by Django 3.2.16 on 2022-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221209_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aboutInfo',
            new_name='aboutinfo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
