# Generated by Django 3.2.16 on 2022-12-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221213_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='blogIdea',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='wordcount',
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
