# Generated by Django 3.2.16 on 2023-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blogsection_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthlyCount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptionType',
            field=models.CharField(choices=[('free', 'free'), ('starter', 'starter'), ('advanced', 'advanced')], default='free', max_length=100),
        ),
    ]
