# Generated by Django 3.2.16 on 2024-05-06 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20230210_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monthlyCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('auditing', 'Auditing'), ('bookkeeping', 'Bookkeeping')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('client', 'Client'), ('personnel', 'Personnel')], default='supervisor', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptionType',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('advanced', 'Advanced')], default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
