# Generated by Django 3.2.16 on 2024-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='department',
            field=models.CharField(blank=True, choices=[('auditing', 'Auditing'), ('bookkeeping', 'Bookkeeping'), ('hr', 'Human Resources')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='user_type',
            field=models.CharField(blank=True, choices=[('supervisor', 'Supervisor'), ('personnel', 'Personnel'), ('client', 'Client')], max_length=100, null=True),
        ),
    ]
