# Generated by Django 3.2.16 on 2024-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20240511_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
