# Generated by Django 3.2.16 on 2024-05-23 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_taskassignmentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignmentcount',
            name='department',
            field=models.CharField(choices=[('auditing', 'Auditing'), ('bookkeeping', 'Bookkeeping')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignmentcount',
            name='personnel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
