# Generated by Django 3.2.16 on 2024-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20240624_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='client',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
