# Generated by Django 3.2.16 on 2024-06-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_assigned_personnel_username_recurringtask_assigned_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='assigned_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_personnel', to='home.profile1'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='home.profile1'),
        ),
    ]
