# Generated by Django 3.2.16 on 2024-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_client_recurringtaskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtaskfile',
            name='file',
            field=models.FileField(upload_to='recurrent_task_files/'),
        ),
    ]
