# Generated by Django 3.2.16 on 2024-07-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_recurringtaskfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrentfiles',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='recurrentfiles',
            name='file',
            field=models.FileField(upload_to='recurrent_task_files/'),
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('files', models.ManyToManyField(blank=True, related_name='task_updates', to='home.RecurrentFiles')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='home.recurringtask')),
            ],
        ),
    ]
