# Generated by Django 3.2.16 on 2022-12-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
