# Generated by Django 3.2.16 on 2022-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_profile_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
